### ISSUE TITLE
AsyncAPI spec v3 support in Bundler

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/bundler#133]
#### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

Remaining tasks:

- [ ] Update to support v3 structures for bundling

**Comment by Souvikns** [comment]
> Would be really cool to have this library work out the gate when we release v3, are any of you interested in scheduling a public call specifically to discuss how to enable this?


Sure @jonaslagoni let me read up on spec3 and see what needs to be changed in bundler to support it, Maybe we can discuss about this at the next spec 3.0 meeting

**Comment by jonaslagoni** [comment]
Not sure how much this change affect your logic: https://v3.asyncapi.com/blog/release-notes-3.0.0#unified-referencing-behaviors

**Comment by Souvikns** [comment]
@jonaslagoni working on a PR, will create a separate logic for spec 3.0 and add a check for the spec inputted in bundler to either use the current logic or the new one.

**Comment by mfroberg** [comment]
I am trying to use the bundle command of the Async API CLI tool v1.4.11. It gives be the error "One of the files you tried to bundle is AsyncAPI v3 format, the bundle command does not support it yet" and refers to this issue #133. 

Since this issue is closed, I am confused. Maybe I am in the wrong place looking for v3 support for the bundle command? Or missing something obvious? :)

**Comment by Souvikns** [comment]
In case you got redirected here looking for v3 support for the bundle CLI command, please check the following issue: https://github.com/asyncapi/cli/issues/1137
